name: CI - Java checks

on:
  pull_request:
    branches: [dev, staging, production]
  push:
    branches: [dev]

jobs:
  java-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set dynamic envs for configuring common_events dependency
        run: |
          echo "COMMON_EVENTS_GH_USER=${{ secrets.COMMON_EVENTS_GH_USER }}" >> $GITHUB_ENV
          echo "COMMON_EVENTS_GH_TOKEN=${{ secrets.COMMON_EVENTS_GH_TOKEN }}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Create settings.xml with env variable
        run: |
          cat <<EOF > settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                  <server>
                      <id>github</id>
                      <username>$COMMON_EVENTS_GH_USER</username>
                      <password>$COMMON_EVENTS_GH_TOKEN</password>
                  </server>
              </servers>
          </settings>
          EOF

      - run: cat settings.xml

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verify dependencies
        run: |
          mvn -s settings.xml -B -DskipTests dependency:resolve

      - name: Build with Maven
        run: mvn -s settings.xml -B clean install

      - name: Run tests
        run: mvn -s settings.xml test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
