name: CI - Java checks

on:
  pull_request:
    branches: [dev, staging, production]
  push:
    branches: [dev]

jobs:
  java-checks:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ secrets.COMMON_EVENT_DEP_GH_USER }}
      GH_TOKEN: ${{ secrets.COMMON_EVENT_DEP_GH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - run: |
          curl -o settings.xml https://raw.githubusercontent.com/AmaliTech-Training-Academy/config-repository-versapath/refs/heads/dev/settings.xml

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verify dependencies
        run: |
          mvn -s settings.xml -B -DskipTests dependency:resolve

      - name: Build with Maven
        run: mvn -s settings.xml -B clean install

      - name: Run tests
        run: mvn -s settings.xml test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Upload service-jar
        uses: actions/upload-artifact@v4
        with:
          name: versapath-user-service-jar
          path: target/*-SNAPSHOT.jar
